// // backend/utils/facts.js
// module.exports.FACTS = [
//   "One hard bounce can hurt your sender reputation and future email delivery.",
//   "Catch-all domains accept any address, even fake ones, so results can be misleading.",
//   "Disposable email addresses expire quickly and rarely lead to real customers.",
//   "Team addresses like info@ or sales@ usually get less engagement than personal emails.",
//   "Keeping your list clean beats clever subject lines for better results.",
//   "Re-checking old lists reduces bounces and protects your sender reputation.",
//   "Some ‘unknown’ replies are temporary blocks like greylisting; try again later.",
//   "Valid emails don’t guarantee inbox placement; they only avoid hard bounces.",
//   "Warm new domains slowly with small, steady sending to build trust.",
//   "SPF, DKIM, and DMARC help mail providers trust your messages.",
//   "Using a consistent From name builds recognition and improves opens.",
//   "Group Gmail, Yahoo, and work domains separately to tune sending.",
//   "Remove inactive contacts regularly to protect reputation and cut costs.",
//   "Typos like gmal.com are common—validate email at signup to catch them.",
//   "Bulk validation finds problems that one-off checks can easily miss.",
//   "Many catch-all results can signal a risky or low-quality list source.",
//   "A clean list saves money and improves performance on every send.",
//   "Greylisting often clears by itself after a retry—no need to panic.",
//   "Recipient DNS problems can make valid addresses look ‘unknown’ temporarily.",
//   "Provider incidents can cause SMTP timeouts; retry later usually works.",
//   "Double opt-in stops fake signups and keeps your list high quality.",
//   "Real-time validation blocks throwaway emails before they reach your list.",
//   "Bounces often cluster by domain—watch for trouble spots and adjust.",
//   "Email lists decay over time; schedule regular re-verification.",
//   "Validate lists before big campaigns to save credits and avoid bounces.",
//   "Role accounts often filter marketing messages or never reply.",
//   "Disposable domains change often; keep your blocklists and checks updated.",
//   "Sending on a steady schedule looks safer to inbox providers.",
//   "Generic link shorteners can trigger filters—use your own domain.",
//   "Large attachments increase filtering and delivery risk; link instead.",
//   "Include a plain-text version to improve deliverability and accessibility.",
//   "Image-only emails perform worse; always include real text content.",
//   "Reverse DNS (PTR) records help providers verify your sending server.",
//   "DMARC reports show spoofing attempts so you can fix authentication.",
//   "Align envelope-from and header-from when possible for cleaner authentication.",
//   "Use TLS for SMTP—encrypted transport is standard and expected.",
//   "Shared IPs share reputation; monitor neighbors’ impact carefully.",
//   "Sudden volume spikes may be throttled; ramp sending gradually.",
//   "Providers score you by domain and IP—track both reputations.",
//   "Seed tests don’t equal real engagement; watch subscriber behavior.",
//   "Removing frequent complainers lowers future spam complaints.",
//   "Encouraging replies increases trust and deliverability over time.",
//   "Sunset policies remove long-inactive contacts and protect sender health.",
//   "Track where signups come from—source quality varies widely.",
//   "CAPTCHA plus validation helps block bots and fake signups.",
//   "Too much personalization can feel spammy—keep it natural.",
//   "Authenticate subdomains you also send from, not just the root.",
//   "Gradual sending ramps look safer than sudden bursts to providers.",
//   "Unstable MX records or missing A records can break delivery.",
//   "New DNS records need time to propagate; expect short delays.",
//   "Best results come from valid addresses who actually engage."
// ];


// // backend/utils/facts.js
// module.exports.FACTS = [
//   "One bad bounce and your reputation takes a nosedive. Ouch.",
//   "Catch-all domains say yes to everyone—like that friend who never says no.",
//   "Disposable emails vanish faster than free donuts at the office.",
//   "info@ never reads your newsletter. Ever.",
//   "A clean list beats a clever subject line—sorry, copywriters.",
//   "Old lists age like milk. Recheck before you hit send.",
//   "‘Unknown’ replies? Usually just the internet saying, ‘Try again later.’",
//   "Valid doesn’t mean inbox—it just means you won’t crash into spam land.",
//   "Warm new domains slowly. Email servers hate sudden enthusiasm.",
//   "SPF, DKIM, and DMARC: your email’s superhero trio.",
//   "Use the same From name—people like familiar faces, even in inboxes.",
//   "Gmail, Yahoo, and work emails all have different moods. Treat them gently.",
//   "Ghost subscribers haunt your list. Exorcise them regularly.",
//   "gmal.com isn’t Gmail. Validate before you embarrass yourself.",
//   "Bulk checks catch sneaky problems your single test never noticed.",
//   "Lots of catch-alls? Your list might be sketchier than a doodle pad.",
//   "A clean list saves cash and keeps servers smiling.",
//   "Greylisting clears up on retry—so breathe, don’t panic.",
//   "DNS hiccups can make real people look fake. Tech gremlins, right?",
//   "Timeouts happen. Even servers need a nap sometimes.",
//   "Double opt-in: because fake signups are bad roommates.",
//   "Real-time validation: stopping throwaway emails faster than you can say ‘oops’.",
//   "Bounces love to travel in groups. Watch the patterns.",
//   "Email lists age like bananas. Verify often.",
//   "Check your list before big sends—your wallet will thank you.",
//   "Role accounts like sales@ rarely read love letters. Skip them.",
//   "Disposable domains change faster than TikTok trends. Stay alert.",
//   "Send regularly. Email providers like routine more than your gym coach.",
//   "Bit.ly links? Spam filters’ favorite snack. Use your own domain.",
//   "Big attachments? Might as well mail a brick. Use links.",
//   "Plain-text emails are boring—but reliable. Like oatmeal.",
//   "All-image emails? Looks pretty, delivers badly. Add text.",
//   "Reverse DNS helps servers recognize you—it’s like showing ID at the door.",
//   "DMARC reports are basically gossip about your domain. Read them.",
//   "Matching From addresses makes you look organized. Fake it till you make it.",
//   "TLS is the seatbelt of email. Don’t drive without it.",
//   "Shared IPs are like roommates—hope they’re tidy.",
//   "Send too fast and servers think you’re yelling. Chill.",
//   "Providers score your domain like teachers grade homework. Be a good student.",
//   "Seed tests are practice exams. Real engagement is the final test.",
//   "Kick out complainers—they’ll just hit ‘spam’ anyway.",
//   "Encourage replies. Emails love attention too.",
//   "Sunset old contacts—they’re ghosting you anyway.",
//   "Track where signups come from. Some places are sketchier than dark alleys.",
//   "CAPTCHA + validation = bouncer for your signup form.",
//   "Over-personalization? Creepy. Stay friendly, not stalker-y.",
//   "Authenticate subdomains too—they want love, not neglect.",
//   "Ramp up volume slowly—no one likes surprise parties from senders.",
//   "MX records without A records? It’s like a mailbox with no house.",
//   "New DNS? Chill, it’s still finding itself.",
//   "Happy lists = happy inboxes. Keep them clean and engaged."
// ];



// backend/utils/facts.js
module.exports.FACTS = [
  "One bad bounce 🚫 can quickly hurt your sender reputation.",
  "Catch-all domains 🤷‍♂️ accept every address—even the fake ones.",
  "Disposable emails 🕒 vanish faster than free donuts at the office 🍩.",
  "That info@ inbox 💤 never reads your newsletter—trust us.",
  "A clean list 🧹 beats a clever subject line every time.",
  "Old email lists age like milk 🥛—recheck before you send.",
  "‘Unknown’ replies 🕓 usually mean the server’s just saying, ‘Try again later.’",
  "Valid doesn’t mean inbox 📬—it only means you dodged a bounce.",
  "Warm up new domains slowly 🔥 so servers don’t freak out.",
  "SPF, DKIM, and DMARC 🦸‍♂️ protect your emails like superheroes.",
  "Use the same From name 👤 to build trust and recognition.",
  "Gmail, Yahoo, and work mailboxes 🏢 all behave differently 😅.",
  "Ghost subscribers 👻 haunt your list—time for a cleanup.",
  "Typing gmal.com instead of gmail.com 😬 happens—validate early.",
  "Bulk checks 🕵️‍♂️ catch sneaky issues your single test misses.",
  "Too many catch-alls 📧 might mean your list is risky.",
  "A clean list 🧹 saves money 💰 and protects your domain reputation.",
  "Greylisting ⏳ usually clears on retry—no need to panic.",
  "DNS hiccups 🌐 can make real people look fake 👀.",
  "Timeouts 💤 happen—sometimes even servers need a nap.",
  "Double opt-in ✉️ keeps fake signups 🧟‍♂️ off your list.",
  "Real-time validation ⚡ blocks throwaway emails before they slip in.",
  "Bounces 🧳 often travel in groups—watch for patterns.",
  "Email lists age like bananas 🍌—verify them regularly.",
  "Always check your list before big sends 💌—your wallet will thank you.",
  "Role accounts like sales@ 💼 rarely read marketing emails 💔.",
  "Disposable domains 📱 pop up faster than TikTok trends.",
  "Send consistently 📅—email providers love predictable routines.",
  "Bit.ly links 🍪 make spam filters hungry—use your own domain.",
  "Big attachments 📦 slow delivery—share links instead 🔗.",
  "Plain-text emails 😐 might be boring, but they’re reliable.",
  "All-image emails 🎨 look great, but deliver badly.",
  "Reverse DNS 🔍 helps servers recognize you—like showing ID at the door.",
  "DMARC reports 🗣️ tell you who’s pretending to be you—read them.",
  "Matching From addresses ✅ makes you look organized and legit.",
  "TLS encryption 🔒 is your email seatbelt—always buckle up 🚗.",
  "Shared IPs 🏠 are like roommates—keep them tidy.",
  "Send too fast 🚀 and servers might think you’re shouting 📢.",
  "Providers score domains 🧾 like teachers grade homework—earn those A’s.",
  "Seed tests 🧪 are practice runs—real engagement is the final exam.",
  "Kick out complainers 😤 before they hit the spam button.",
  "Encourage replies 💬—emails love real conversations too.",
  "Sunset old contacts 🌇 before they start ghosting 👻.",
  "Track where signups come from 🔍—some sources are sketchy.",
  "CAPTCHA + validation 🧍‍♂️ keeps bots out of your signup form.",
  "Over-personalization 👀 feels creepy—keep it human and friendly 😅.",
  "Authenticate subdomains 🔐 so every sender looks trustworthy.",
  "Ramp up slowly 📈—servers hate sudden surprises.",
  "MX without A records 📮 is like a mailbox with no house 🏚️.",
  "New DNS? 🧭 Give it time—it’s still finding itself.",
  "Happy lists 😊 mean happy inboxes 📬—keep them clean and engaged."
];
